### ISSUE TITLE
Have problem in abessMultinomial

### ISSUE THREAD

**Issue by bored2020** [abess-team/abess#263]
When I want to use abess in multi classfication,I use the abessMultinomial and run the example code
```
from abess.linear import abessMultinomial
from abess.datasets import make_multivariate_glm_data
import numpy as np
np.random.seed(12345)
data = make_multivariate_glm_data(n = 100, p = 50, k = 10, M = 3, family = 'multinomial')
model = abessMultinomial(support_size = [10])
model.fit(data.x, data.y)
model.predict(data.x)

```
And I get an int 47,but I think it should get a array of the class such as .
```
array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
```

I'm so sorry to bother you again.And thanks a lot for yours help.

**Comment by Jiang-Kangkang** [comment]
Sorry, that is a bug of our code.We will fix it as soon as possible and remind you after finishing. Thank you for reporting the bug!

**Comment by Jiang-Kangkang** [comment]
Hi, we have fix the problem at latest version on github, you can install the latest version following the [guideline](https://abess.readthedocs.io/en/latest/Installation.html) of latest release. We will update at Pypi soon. @bored2020

**Comment by Mamba413** [comment]
Good. I will close this issue.

**Comment by bored2020** [comment]
Thanks a lot,I was lucky to meet both of you.
