### ISSUE TITLE
Request for the Generalization to Ordinal Logistics Regression

### ISSUE THREAD

**Issue by chenxy-sysu** [abess-team/abess#303]
Your method performs quite well on high-dimensional linear models. I am curious about whether it will work on ordinal logistics regression, and this also seems to be a meaningful generalization. Will you implement this new feature in the near future? Thanks!

**Comment by Mamba413** [comment]
> Your method performs quite well on high-dimensional linear models. I am curious about whether it will work on ordinal logistics regression, and this also seems to be a meaningful generalization. Will you implement this new feature in the near future? Thanks!

We have add ordinal logistic regression in https://github.com/abess-team/abess/pull/304. It now has R interface, and Python's interface is coming soon.
