### ISSUE TITLE
install R package from github via devtools::install_github()

### ISSUE THREAD

**Issue by bbayukari** [abess-team/abess#305]
I meet trouble when I install R package abess from github directly. 

I have delete original abess, and then just use the code "devtools::install_github("abess-team/abess/R-package")" in RStudio, and this is the error information:

Downloading GitHub repo abess-team/abess@HEAD
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All                         
2: CRAN packages only          
3: None                        
4: Rcpp (1.0.7 -> 1.0.8) [CRAN]

Enter one or more numbers, or an empty line to skip updates: 
√  checking for file 'C:\Users\ustc\AppData\Local\Temp\RtmpKkyovB\remotes32f06dd94478\abess-team-abess-4d97f97\R-package/DESCRIPTION' ... 
-  preparing 'abess':
√  checking DESCRIPTION meta-information ... 
-  cleaning src
-  installing the package to process help pages
         -----------------------------------
-  installing *source* package 'abess' ...
   ** using staged installation
   cp: cannot stat '../include': No such file or directory
   cp: cannot stat '../src/*.cpp': No such file or directory
   cp: cannot stat '../src/*.h': No such file or directory
   ERROR: configuration failed for package 'abess'
-  removing 'C:/Users/ustc/AppData/Local/Temp/RtmpEXjWyu/Rinst72056862b16/abess'
         -----------------------------------
   ERROR: package installation failed
Error: Failed to install 'abess' from GitHub:
  System command 'Rcmd.exe' failed, exit status: 1, stdout + stderr (last 10 lines):
E>       -----------------------------------
E> * installing *source* package 'abess' ...
E> ** using staged installation
E> cp: cannot stat '../include': No such file or directory
E> cp: cannot stat '../src/*.cpp': No such file or directory
E> cp: cannot stat '../src/*.h': No such file or directory
E> ERROR: configuration failed for package 'abess'
E> * removing 'C:/Users/ustc/AppData/Local/Temp/RtmpEXjWyu/Rinst72056862b16/abess'
E>       -----------------------------------
E> ERROR: package installation failed

**Comment by Mamba413** [comment]
Thanks for your question. 

Unfortunately, it is not possible to install `abess` with `devtools::install_github()`, since the repo of `abess` uses git submodules. I want to point that, not just or repo has this issue. For example, this issue also occurs in the popular machine learning package `xgboost` (See https://github.com/dmlc/xgboost/issues/6170). 

We will also update the instructions in https://abess.readthedocs.io/en/latest/Installation.html, which is not correct now.
