### ISSUE TITLE
Can't find cpp function

### ISSUE THREAD

**Issue by bbayukari** [abess-team/abess#306]
In my fork repo, the developing part in "bbayukari/abess/develop-ordinal" worked well before, but the new version which I want to PR to upstream in "bbayukari/abess/ordinal" didn't work(not only my part didn't work, but all models can't find the api). In the new version, I locate the cpp code at abess/src where isn't in R-package, that's the only difference between the two versions.

After clone the code in "bbayukari/abess/ordinal", then "install and restart", and test simply like:

```r
dataset <- generate.data(150,100,3)
abess(dataset[["x"]],dataset[["y"]])
```

then,

```r
Error in abessGLM_API(x = x, y = y, n = nobs, p = nvars, normalize_type = normalize,  : 
  could not find function "abessGLM_API"
Called from: abess.default(dataset[["x"]], dataset[["y"]])
```

**Comment by Mamba413** [comment]
Hi! Thanks for your question. Which repository did you fork? "abess-team/abess" or "Mamba413/abess"?

**Comment by bbayukari** [comment]
It forked from abess-team/abess. And the new version "bbayukari/abess/ordinal" which did not work is modified based on the "abess-team/abess/master" branch.

**Comment by Mamba413** [comment]
I have updated the `abess` repo a few hours ago. I believe this update can address this issue.

**Comment by Mamba413** [comment]
From your report on https://github.com/abess-team/abess/pull/304, I believe this issue has been addressed. 

Let me try to explain why you encounter this issue. I think `RcppExports.R` and `RcppExports.cpp` are wrongly deleted, and thus, the `abessGLM_API` implemented within it cannot be searched. 

I edited the `configure.win` and `configure.ac` in R-package. The two files will automatically generate `RcppExports.R` and `RcppExports.cpp` when Github Actions triggering. So, this issue can be fixed.

Again, thanks for your question. Please feel free to contact us.
