### ISSUE TITLE
support exponential correlation structure for the `abess` python library

### ISSUE THREAD

**Issue by Mamba413** [abess-team/abess#418]
`abess` would be even more helpful if `make_glm_data` and `make_multivariate_glm_data` can support simulating datasets associated with an exponential correlation structure. This structure is widely considered in recent literature (e.g. https://arxiv.org/pdf/2104.12576.pdf).

**Comment by oooo26** [comment]
This is available now by giving an argument `corr_type="exp"` and I will close the issue. Thank you.
