### ISSUE TITLE
the class `OrdinalRegression` can’t be imported from the module `abess.linear`

### ISSUE THREAD

**Issue by Everglow00** [abess-team/abess#428]
Hello, I'm trying to running `make html` in command line to convert comments to `.html` files, but there are soming warnings and errors in compiling the basic examples like cox regression. The warnings show that the class ` OrdinalRegression `  can’t be imported from the module  ` abess.linear `. Then I try to delete my comments, but there are still warnings and errors.
Here are the warnings:
```
WARNING: autodoc: failed to import class OrdinalRegression' from module' abess. linear
AttributeError: module’ abess. linear' has no attribute’ OrdinalRegression'
checking consistency... D: \My app \Gi thubDesktop \abess \docs \Tutorial\1-g 1m \README. rst: WARNING: document isn' t included in any toctree
D: \My app \Gi thubDesktop \abess \docs \Tutorial \2- pca \README. rst: WARNING: document isn' t included in any toctree
app\Gi thubDesktop \abess \docs \Tutorial \3 -advanced features \README.rst WARNING: document isn't included in any toctree
D: \My app \Gi thubDesktop \abess \docs \Tutorial \4-computation-tips \README. rst: WARNING: document isn' t included in any toctree
D: \My app \Gi thubDesktop \abess \docs \Tutorial \5-scikit-learn-connection \README. rst: WARNING: document isn' t included in any toctree 
D: \My app \Gi thubDesktop \abess \docs \Tutorial \README. rst: WARNING: document isn' t inc luded in any toctree 
```

**Comment by oooo26** [comment]
Hi @Everglow00 , thank you for contributing the document. I find this error information may be caused by an old version of ABESS. To build the document, you need to install [the latest version](https://abess.readthedocs.io/en/latest/Installation.html#latest-version) instead. It will be work then.

**Comment by Mamba413** [comment]
Hi @Everglow00 , thanks for reporting the issue you found. I recommend you describe this issue by pasting the text rather than the screenshot. It will help the other users easily find the solution to similar issues.

**Comment by Everglow00** [comment]
Thanks for your replies and advices, and the problem has been solved. Besides, I have redescribed my problem to make sure that other users can find the solution easier with similar problems. Thank you!
