### ISSUE TITLE
Use same keyword arguments for sample weight as sklearn

### ISSUE THREAD

**Issue by lindnemi** [abess-team/abess#454]
First of all: Thank you for the great package, it has been very helpful. Now to my suggestion:

Abess uses `weight`
https://abess.readthedocs.io/en/latest/Python-package/linear/Logistic.html?highlight=score#abess.linear.LogisticRegression.fit
Sklearn uses `sample_weight`
https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html#sklearn.linear_model.LogisticRegression.fit

I'm using both in a project and it would be helpful if abess followed the sklearn convention.

**Comment by Mamba413** [comment]
An excellent suggestion! We going to modify our API in the future version.

**Comment by Mamba413** [comment]
@lindnemi , we have used the same keyword arguments for `sample_weight` as `scikit-learn`. You can reinstall `abess` via github to enjoy this new feature. We going to support this feature in the next pypi&conda version.

**Comment by lindnemi** [comment]
Thank you :) That was really quick!
