### ISSUE TITLE
Samples with zero weight can affect the result.

### ISSUE THREAD

**Issue by chenpnn** [abess-team/abess#458]
**Describe the bug**

I want to check that whether setting sample weight to 0 is equivalent to removing corresponding samples. However, in the following example, `coef1` and `coef2` are different. Does it means that samples with zero weight can still affect the result?

**Code for Reproduction**

```python
import numpy as np
from abess.linear import MultinomialRegression
from abess.datasets import make_multivariate_glm_data

n, p = 100, 50
np.random.seed(12345)
data = make_multivariate_glm_data(n=n, p=p, k=10, M=3, family='multinomial')

# construct dataset1 with 100 samples
X1, y1 = data.x, data.y
w1 = np.ones(n)
model1 = MultinomialRegression(support_size=10)
model1.fit(X1, y1, weight=w1)
coef1 = model1.coef_

# construct dataset2 by adding 100 different samples to dataset1
# simultaneously set weight to 0 for these additional 100 samples
X2 = np.vstack([data.x, -data.x])
y2 = np.vstack([data.y, data.y])
w2 = np.ones(n * 2)
w2[n:] = 0
model2 = MultinomialRegression(support_size=10)
model2.fit(X2, y2, weight=w2)
coef2 = model2.coef_
```
Thanks!

**Comment by oooo26** [comment]
Thank you for reporting the problem!

We found that although our algorithms can deal with zero-weight samples, these redundant parts will still affect the chosen sparsity, for example, by making BIC larger. 

To avoid it, we drop the zero-weight ones in advanced before the main process. It could fix the problem fundamentally.
