### ISSUE TITLE
Installation Error: Could not find a version that satisfies the requirement setuptools>=42

### ISSUE THREAD

**Issue by chenpnn** [abess-team/abess#475]
**Installation Error**

When I try to install abess from GitHub directly using the command
```cmd
cd ./python
pip install .
```
some errors were reported as shown in the following picture

![eb959d4b4b8fd66db4e482f33704238](https://user-images.githubusercontent.com/44487601/212816719-92ae9054-a712-4f76-af2f-03e287a77e42.png)

Is there anything wrong with my computer or the source code of abess?

Thanks!

**Comment by Mamba413** [comment]
@chenpnn ，can you paste the Error information here rather than using screenshot? Also, can you provide some information for your python environment?

**Comment by Mamba413** [comment]
@chenpnn ，it seems that `setuptools>=42` is not support by Python 3.9.1? Can you make another python environment and try it again?

**Comment by Mamba413** [comment]
@oooo26 , can you recommend you python version to @chenpnn

**Comment by oooo26** [comment]
Hi @chenpnn, could you please try to update the dependencies by another source like `pip install setuptools>=42 -i https://pypi.tuna.tsinghua.edu.cn/simple` first? Because the `SSLError` seems a network problem.

**Comment by oooo26** [comment]
Besides, when I create a new environment with `conda create -n py391 python=3.9.1`, it has already included `setuptools-65.6.3`. Hence I think there exists a suitable version on this environment.

**Comment by chenpnn** [comment]
> Hi @chenpnn, could you please try to install by another pip source like `pip install . -i https://pypi.tuna.tsinghua.edu.cn/simple`? Because the `SSLError` seems a network problem.

Thanks, this method works for me!
