### ISSUE TITLE
All types of tune go wrong in PCA model

### ISSUE THREAD

**Issue by bbayukari** [abess-team/abess#484]
**Describe the bug**

All types of tune go wrong in PCA model, include "gic", "aic", "bic", "ebic" and "cv". Specifically, all information metric methods return 0; the result of "cv" method monotonically decreases as `support_size` increases so it's useless for selecting `support_size`. 

**Code for Reproduction**

```r
n <- 10000
p <- 5
support_size <- 3
dataset <- generate.spc.matrix(n, p, support_size, snr = 100, seed = 1)

for(ic_type in c("gic", "aic", "bic", "ebic")){
  spca_fit <- abesspca(dataset[["x"]], tune.type = ic_type)
  if(all(spca_fit[["tune.value"]] == 0)){
    print(sprintf("tune.value of %s is all zero!", ic_type))
  } 
}

spca_fit2 <- abesspca(dataset[["x"]], tune.type = "cv")
if(!is.unsorted(-spca_fit2[["tune.value"]])){
  print("tune.value of cv is sorted!")
}
```

Results:

```
[1] "tune.value of gic is all zero!"
[1] "tune.value of aic is all zero!"
[1] "tune.value of bic is all zero!"
[1] "tune.value of ebic is all zero!"
[1] "tune.value of cv is sorted!"
```

**Desktop (please complete the following information):**
 - OS: x86_64-w64-mingw32
 - R version 4.2.1
 - Package Version 0.4.6

**Comment by Mamba413** [comment]
I think this bug is relate to a recent pull request.https://github.com/abess-team/abess/pull/477#issue-1561278366

**Comment by oooo26** [comment]
Yep, there is a change here: 
- `Kfolds` should be 1 to enable IC;
- `ic_type` should be 0 to use test loss in CV.

However, CV may not be a good strategy in PCA. (As you found, it will return the largest sparsity)

**Comment by Mamba413** [comment]
I believe this issue has been addressed. So I will remove the `bug` label.
