### ISSUE TITLE
[R-package] abess fails with one feature

### ISSUE THREAD

**Issue by sebffischer** [abess-team/abess#493]
**Describe the bug**

`abess::abess()` from R package fails when there is only one feature. 

**Code for Reproduction**
``` r
library(abess)
library(data.table)

x = data.table(x = sample(100, size = 100))
y = factor(sample(c("a", "b", "c"), size = 100, replace = TRUE))

abess(x = x, y = y, family = "multinomial")
#> Error in Matrix::Matrix(x[, -y_dim], sparse = TRUE, dimnames = list(vn, : length of 'dimnames' [1] not equal to array extent
```

<sup>Created on 2023-03-01 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Version: ‘0.4.7’

This did not happen in previous releases (you broke the CI of mlr3extralearners)

**Comment by bbayukari** [comment]
Hey, we have fixed this issue and the code for reproduction has been able to pass. We will soon publish a new abess version to completely address this issue. 

Is there something else shall we do?

**Comment by sebffischer** [comment]
Thanks! 
No thats it :)
