### ISSUE TITLE
Segmentation fault using v0.4.6 on Linux

### ISSUE THREAD

**Issue by ecm200** [abess-team/abess#496]
**Describe the bug**

When installing `v0.4.6` any calls to the `abess` library causes a segmentation fault.

The same simple script with `v0.4.5` results in a normal execution.

**Code for Reproduction**

```python
from abess.linear import LinearRegression
from abess.datasets import make_glm_data
import numpy as np
np.random.seed(12345)
data = make_glm_data(n = 100, p = 50, k = 10, family = 'gaussian')
model = LinearRegression(support_size = 10)
model.fit(data.x, data.y)

print(model.predict(data.x)[:4])
```

Using `v0.4.6` results  in the following error:

![image](https://user-images.githubusercontent.com/34489160/223442661-2221698f-434c-4fca-8b88-3ae4c18c8976.png)

**Expected behavior**

I expected the predictions to be printed without segmentation fault.

Example run with `v0.4.5`:

![image](https://user-images.githubusercontent.com/34489160/223442515-e68cb530-5c7c-451c-815c-18ccd1e9f693.png)

**Desktop (please complete the following information):**
 - OS: Linux-5.4.0-1098-azure-x86_64-with-glibc2.17, 64bit
 - Python Version: 3.8.12
 - Package Version: 0.4.6

**Comment by oooo26** [comment]
Hi @ecm200, we have confirmed the bug and so sorry for the inconvenience. It seems the problem on the latest wheels. Please temporarily use the old version or install from source `pip install abess==0.4.6 --no-binary :all:`.

Thank you for the feedback! We will fix the problem soon.

**Comment by ecm200** [comment]
No worries at all, no need to apologize.
Glad I could help pointing something out.

As I did above, I confirmed that `v0.4.5` is indeed working as expected.

**Comment by ecm200** [comment]
> Hi @ecm200, we have confirmed the bug and so sorry for the inconvenience. It seems the problem on the latest wheels. Please temporarily use the old version or install from source `pip install abess==0.4.6 --no-binary=abess`.
> 
> Thank you for the feedback! We will fix the problem soon.

Thanks for the workaround, I can confirm that I've built the package from source, and it is now running successfully using `v0.4.6`.

**Comment by oooo26** [comment]
It is a weird bug... I have checked the wheels built by our [PyPI workflow](https://github.com/abess-team/abess/blob/master/.github/workflows/pypi.yml) and the problem exists even for:
- the latest ABESS code;
- a newer version of `cibuildwheel`, e.g. `v2.12.0`;

However I haven't reproduced it in a simpler demo package. One solution is to revert the version of `cibuildwheel` to `v2.3.1`, which used to build ABESS v0.4.5. 

@Mamba413 Do u think we should revert the version and publish a workable version first?

**Comment by Mamba413** [comment]
@oooo26 ，thanks! Just revert the version of `cibuildwheel`. Also, shall we report this bug to the team for `cibuildwheel`?

**Comment by oooo26** [comment]
> @oooo26 ，thanks! Just revert the version of `cibuildwheel`. Also, shall we report this bug to the team for `cibuildwheel`?

Sure, I will revert it. And actually I tend to try making a simpler demo before reporting.
