### ISSUE TITLE
Perhaps a typo in the online tutorial for multi-response linear regression

### ISSUE THREAD

**Issue by brtang63** [abess-team/abess#501]
The loss function seems incorrect in the first section of the online tutorial. Should the **2-norm** of matrices be changed to the **Frobenius norm** instead? Both for R & Python tutorials.

[R tutorial](https://abess-team.github.io/abess/articles/v06-MultiTaskLearning.html)
[Python tutorial](https://abess.readthedocs.io/en/latest/auto_gallery/1-glm/plot_3_MultiTaskLearning.html)

**Comment by Mamba413** [comment]
would you mind correct this for us?

**Comment by brtang63** [comment]
Sure. With my pleasure. I've opened a pull request.
