### ISSUE TITLE
How I can aviod intercept when I do abess in R

### ISSUE THREAD

**Issue by ZjpWei** [abess-team/abess#511]
I'm trying to use Abess in R, I didn't find any option in argument for avioding intercept. I also try to use fomular: y ~ 0 + x to aviod intercept but fail. 

Is there a way to do that?

**Comment by Mamba413** [comment]
Great! This feature request is very similar to https://github.com/abess-team/abess/issues/507 for the Python interface. We are implementing this feature now.  And I make a note that implementing this feature in C++ may take some time. Thank you for bringing this to my attention.
