### ISSUE TITLE
[Feature] Release new version of `abess` on PyPI and Conda

### ISSUE THREAD

**Issue by Mamba413** [abess-team/abess#517]
I think it is time to release a new version on `conda` and `pypi` since we have already added new features: 

- https://github.com/abess-team/abess/pull/516

- https://github.com/abess-team/abess/pull/513

and we have also addressed some issues.

**Comment by oooo26** [comment]
No problem! Let me publish a pre-release version to PyPI and check if it works fine.

**Comment by bbayukari** [comment]
abess version 0.4.8 has been released on CRAN.
