### ISSUE TITLE
mlr3extralearners JOSS publication author?

### ISSUE THREAD

**Issue by bblodfon** [abess-team/abess#544]
Hi! I am part of the `mlr3` team, and wanted to know who has implemented the 2 abess learners in `mlr3extralearners` ([classification learner code](https://github.com/mlr-org/mlr3extralearners/blob/main/R/learner_abess_classif_abess.R#L2))? I see author as `abess-team` and that's not person-specific :)

We would like to invite the author for the JOSS publication, see issue [here](https://github.com/mlr-org/mlr3extralearners/issues/358). I asked @bbayukari but I might be wrong and never got any response either!

Thanks, John

**Comment by bblodfon** [comment]
Hi @Mamba413 ! Maybe you can quickly comment on the above or know someone who can? Thanks!

**Comment by Mamba413** [comment]
Hi @bblodfon ! Thanks for this author invitation : ). To my knowledge, it is Zezhi Wang (@bbayukari ) implemented the 2 `abess` learners in `mlr3extralearners`. He's affiliation information is attached below.

Zezhi Wang
Department of Statistics and Finance/International Institute of Finance, School of Management, University of Science and Technology of China, Hefei, Anhui, China

**Comment by bblodfon** [comment]
Thanks, we will add him in the list then! :)

**Comment by bblodfon** [comment]
@Mamba413 Hi Jin! Do you maybe know if Zezhi has an ORCHID number?

**Comment by bbayukari** [comment]
Yes, I have. You can find it here: https://orcid.org/0000-0001-6988-5853. Thank you!

**Comment by Mamba413** [comment]
> Yes, I have. You can find it here: https://orcid.org/0000-0001-6988-5853. Thank you!

@bblodfon , Zezhi had replied to you : ).
